# Generated by Django 4.2.7 on 2025-07-15 06:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="last_activity",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
