# Generated by Django 4.2.7 on 2025-06-22 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('INVENTORY', 'Inventory Reports'), ('ASSIGNMENT', 'Assignment Reports'), ('MAINTENANCE', 'Maintenance Reports'), ('COMPLIANCE', 'Compliance & Audit Reports'), ('ANALYTICS', 'Analytics & Insights')], max_length=20)),
                ('description', models.TextField()),
                ('sql_query', models.TextField(blank=True)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('columns', models.JSONField(blank=True, default=list)),
                ('accessible_by_roles', models.JSONField(default=list, help_text='List of user roles that can access this report')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReportGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filters_applied', models.JSONField(default=dict)),
                ('date_range_start', models.DateField(blank=True, null=True)),
                ('date_range_end', models.DateField(blank=True, null=True)),
                ('total_records', models.PositiveIntegerField(default=0)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('file_format', models.CharField(default='PDF', max_length=10)),
                ('generation_started', models.DateTimeField(auto_now_add=True)),
                ('generation_completed', models.DateTimeField(blank=True, null=True)),
                ('generation_failed', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='reports.reporttemplate')),
            ],
        ),
    ]
