# Generated by Django 4.2.7 on 2025-06-22 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCodeScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(choices=[('VERIFICATION', 'Device Verification'), ('LOCATION_UPDATE', 'Location Update'), ('ASSIGNMENT_CHECK', 'Assignment Check'), ('MAINTENANCE', 'Maintenance Scan'), ('AUDIT', 'Audit Scan'), ('GENERAL', 'General Scan')], default='VERIFICATION', max_length=20)),
                ('device_status_at_scan', models.CharField(max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('gps_coordinates', models.CharField(blank=True, max_length=100)),
                ('verification_success', models.BooleanField(default=True)),
                ('discrepancies_found', models.TextField(blank=True)),
                ('actions_taken', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('assigned_staff_at_scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_verifications', to='inventory.staff')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_scans', to='inventory.device')),
                ('device_location_at_scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_verifications', to='inventory.location')),
                ('scan_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.location')),
                ('scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
