# Generated by Django 4.2.7 on 2025-06-22 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('IT_ADMINISTRATOR', 'IT Administrator'), ('IT_OFFICER', 'IT Officer'), ('DEPARTMENT_HEAD', 'Department Head'), ('MANAGER', 'Manager'), ('GENERAL_STAFF', 'General Staff'), ('AUDITOR', 'Auditor'), ('VENDOR', 'Vendor/External')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('permissions', models.JSONField(default=dict, help_text='Detailed permissions configuration')),
                ('can_view_all_devices', models.BooleanField(default=False)),
                ('can_manage_assignments', models.BooleanField(default=False)),
                ('can_approve_requests', models.BooleanField(default=False)),
                ('can_generate_reports', models.BooleanField(default=True)),
                ('can_manage_users', models.BooleanField(default=False)),
                ('can_system_admin', models.BooleanField(default=False)),
                ('restricted_to_own_department', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_roles', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, help_text='Department scope for this role', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.department')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='authentication.userrole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'role', 'department')},
            },
        ),
    ]
